export const fields=[
{id:'north',tenant:'alpha',name:'North field',crop:'Corn',area:42.8,location:'Chatham-Kent · Ontario',geometry:{type:'Polygon',coordinates:[[[-82.19,42.43],[-82.18,42.432],[-82.176,42.423],[-82.187,42.421],[-82.19,42.43]]]}},
{id:'south',tenant:'alpha',name:'River bend',crop:'Soybeans',area:31.2,location:'Chatham-Kent · Ontario',geometry:{type:'Polygon',coordinates:[[[-82.18,42.415],[-82.171,42.418],[-82.168,42.41],[-82.179,42.407],[-82.18,42.415]]]}},
{id:'west',tenant:'beta',name:'West pasture',crop:'Corn',area:26.4,location:'Chatham-Kent · Ontario',geometry:{type:'Polygon',coordinates:[[[-82.21,42.43],[-82.20,42.43],[-82.20,42.42],[-82.21,42.42],[-82.21,42.43]]]}}
];
export const kelvinToCelsius=k=>Math.round((k-273.15)*10)/10;
export const metersPerSecondToKmh=v=>v*3.6;
export function listFields(tenant){if(!['alpha','beta'].includes(tenant))throw Error('UNAUTHORIZED');return fields.filter(f=>f.tenant===tenant)}
function fieldFor(tenant,id){const f=listFields(tenant).find(f=>f.id===id);if(!f)throw Error('NOT_FOUND');return f}
const cycles=[6,12].map(h=>({id:`cycle-${String(h).padStart(2,'0')}`,evidence_type:'forecast',source_id:'synthetic-weather-v1',source_name:'Ontario regional outlook · simulation',source_version:'1.0.0',rights_policy_ref:'synthetic-local-demo',initialization_at:`2026-09-12T${String(h).padStart(2,'0')}:00:00Z`,issued_at:`2026-09-12T${String(h+1).padStart(2,'0')}:00:00Z`,available_at:`2026-09-12T${String(h+2).padStart(2,'0')}:00:00Z`,ingested_at:`2026-09-12T${String(h+2).padStart(2,'0')}:05:00Z`,valid_from:'2026-09-12T15:00:00Z',valid_until:'2026-09-15T15:00:00Z',native_resolution_m:3000,field_resolved:false,temperature_K:h===12?296.15:295.15,wind_m_s:3.5,rain_mm:h===12?8.4:5.2,accumulation_start:'2026-09-12T15:00:00Z',accumulation_end:'2026-09-13T15:00:00Z',wind_direction:'SSW',wind_gust_m_s:6.7,relative_humidity_pct:68,calibration:'Single simulated model run · probability not estimated',hourly:Array.from({length:13},(_,i)=>({hour:i*6,temperature_K:293.15+Math.sin(i*1.4)*5,rain_mm:(h===12?[0,0.4,3.4,4.6,1.2,0,0,0.2,0.6,0,0,0,0]:[0,0.4,1.4,3.4,1.2,0,0,0.2,0.6,0,0,0,0])[i]}))}));
export function brief(tenant,id,asOf='2026-09-12T15:00:00Z',scenario='normal'){
 const field=fieldFor(tenant,id),time=Date.parse(asOf);if(!Number.isFinite(time))throw Error('INVALID_TIME');
 if(!['normal','missing','stale','withdrawn','unsupported'].includes(scenario))throw Error('INVALID_SCENARIO');
 let forecast=cycles.filter(c=>Date.parse(c.available_at)<=time&&Date.parse(c.ingested_at)<=time).at(-1)||null;
 let status=!forecast||id==='south'||scenario==='missing'?'missing':scenario==='withdrawn'?'withdrawn':scenario==='unsupported'?'unsupported':scenario==='stale'||time-Date.parse(forecast.issued_at)>18*3600000?'stale':'fresh';
 if(['missing','withdrawn','unsupported'].includes(status))forecast=null;
 const explanations={fresh:forecast?`The simulated outlook brings ${forecast.rain_mm} mm of rain over the next 24 hours, concentrated overnight. A recent field check is still needed to assess access conditions.`:'Forecast unavailable.',missing:'Insufficient evidence. A required forecast input is missing; field conditions are unknown.',stale:'Insufficient evidence. The forecast is older than the demo freshness limit; current conditions are unknown.',withdrawn:'The source has been withdrawn. Dependent assessments are unavailable, including in replay.',unsupported:'This field is outside the supported fixture coverage. Conditions are unknown.'};
 return {field,as_of:asOf,status,explanation:explanations[status],forecast,rule_version:'fixture.field-brief.v1',observation:{evidence_type:'field_observation',status:'stale',observed_at:'2026-09-09T10:00:00Z',available_at:'2026-09-09T12:00:00Z',observer:'Field scout · demo persona',method:'Visual inspection · no instrument reading',review_status:'Unreviewed',text:({north:'Walked the west access track at 06:00 local. Surface was firm with shallow standing water in the wheel ruts near the gate. No rain gauge reading was taken. Check the low spot again after the next rainfall.',south:'Checked the river-side entrance. The upper track was dry; the shaded section remained soft underfoot. No soil moisture reading or rainfall total was recorded.',west:'Walked the north headland. No standing water along the access route at the time of the visit. Ground conditions deeper in the field were not checked.'})[id]},missing_inputs:['recent_local_rain_observation'],synthetic:true};
}
export function evidence(tenant,id,asOf,scenario){const b=brief(tenant,id,asOf,scenario);return {field_id:id,forecast:b.forecast,observation:b.observation,status:b.status,rule_version:b.rule_version}}
