import { useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowRight, CheckCircle2, ExternalLink, RefreshCw, Users } from 'lucide-react';
import type { AnalystDashboard, ComparisonMetric, ComparisonResult, Evidence } from '../contracts';

const stamp = (s: string) => new Date(s).toISOString().replace('T', ' ').replace('.000Z', ' UTC');
const number = (n: number | null) => n === null ? '—' : Number(n.toFixed(3)).toString();
const title = (m: ComparisonMetric) => ({ temperature_c: 'Temperature at the hour', precipitation_mm: 'Precipitation in the preceding hour', precipitation_probability: 'Chance of >0.1 mm in the preceding hour' })[m];
async function api<T>(url: string, body?: unknown): Promise<T> {
  const r = await fetch(url, body === undefined ? undefined : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const p = await r.json(); if (!r.ok) throw new Error(p.error || 'Request failed'); return p;
}

function OutcomeForm({ item, refresh }: { item: ComparisonResult; refresh: () => void }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  if (item.mode === 'demo') return <p className="analyst-note">Synthetic examples are read-only. Real observations are entered only in Live.</p>;
  if (Date.parse(item.validTo) > Date.now()) return <p className="analyst-note">Awaiting the end of the verification period. No score is assigned yet.</p>;
  return <details className="comparison-entry"><summary>Record a sourced observation</summary><p>Use a complete observation for {stamp(item.validFrom)} to {stamp(item.validTo)}. Radar requires a quantitative precipitation estimate for the full hour; a single reflectivity image is insufficient.</p>
    <form onSubmit={async event => { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api('/api/comparisons/' + item.id + '/outcome', { metric: item.metric === 'temperature_c' ? 'temperature_c' : 'precipitation_mm', value: Number(f.get('value')), validFrom: item.validFrom, validTo: item.validTo, sourceType: f.get('sourceType'), sourceUrl: f.get('sourceUrl'), sourceName: f.get('sourceName'), latitude: Number(f.get('latitude')), longitude: Number(f.get('longitude')), coverageComplete: true, reviewed: true, note: f.get('note') }); refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>
      <div className="analyst-form-grid"><label>Observed value ({item.metric === 'temperature_c' ? '°C' : 'mm'})<input name="value" type="number" step="any" required /></label>
      <label>Observation source<select name="sourceType"><option value="station">Station measurement</option>{item.metric !== 'temperature_c' && <option value="radar_estimate">Radar precipitation estimate</option>}</select></label>
      <label>Station / product name<input name="sourceName" required minLength={2} maxLength={150} /></label><label>Source URL<input name="sourceUrl" type="url" placeholder="https://…" pattern="https://.*" required /></label>
      <label>Observed latitude<input name="latitude" type="number" step="any" required /></label><label>Observed longitude<input name="longitude" type="number" step="any" required /></label></div>
      <p>Reference point: {item.latitude}, {item.longitude}. Observation must be within 5 km; spatial representativeness still needs review.</p>
      <label>Coverage, units and source notes<textarea name="note" minLength={10} maxLength={1000} required /></label>
      <label className="review-check"><input type="checkbox" required /> I inspected this source and verified the metric, units, exact period and complete coverage. This observation will be frozen.</label>
      {error && <p role="alert" className="inline-error">{error}</p>}<button disabled={busy} className="primary-button">{busy ? 'Recording…' : 'Record observation and evaluate'}</button>
    </form></details>;
}

function CaseCard({ item, refresh }: { item: ComparisonResult; refresh: () => void }) {
  const s = item.summary;
  return <article className="comparison-card"><div className="section-heading"><div><span className="eyebrow">{item.mode === 'demo' ? 'SYNTHETIC EXAMPLE' : 'FROZEN COMPARISON'}</span><h3>{item.placeName}</h3></div><span className={'tag ' + (item.outcome ? 'recent' : 'unknown')}>{item.outcome ? 'Evaluated' : 'Awaiting observation'}</span></div>
    <h4>{title(item.metric)}</h4><p className="comparison-window">{item.validFrom === item.validTo ? stamp(item.validTo) : stamp(item.validFrom) + ' → ' + stamp(item.validTo)}</p>
    <div className="comparison-values"><div><span>Analyst mean · {s.count} voices</span><strong>{number(s.mean)}<small> {item.unit}</small></strong><p>Range {number(s.min)}–{number(s.max)} {item.unit}</p></div><div><span>{item.baseline.provider}</span><strong>{number(item.baseline.value)}<small> {item.unit}</small></strong><p>Frozen {stamp(item.baseline.fetchedAt)}</p></div><div><span>{item.outcome ? item.outcome.sourceType === 'radar_estimate' ? 'Radar estimate' : 'Station observation' : 'Outcome'}</span><strong>{item.outcome ? number(item.outcome.value) : '—'}<small> {item.outcome ? item.outcome.metric === 'temperature_c' ? '°C' : 'mm' : ''}</small></strong><p>{item.outcome?.sourceName ?? 'Not observed yet'}</p></div></div>
    {item.outcome && <div className="comparison-score"><CheckCircle2 size={18} /><div><strong>{s.scoreName} · lower is better</strong><p>Analyst mean: {number(s.consensusScore)} · Baseline: {number(s.baselineScore)} · Improvement: {number(s.improvement)}</p><small>Positive improvement means lower error in this case. One case does not establish forecasting skill.{item.outcome.sourceType === 'radar_estimate' ? ' These scores are against a radar estimate, not confirmed ground truth.' : ''}</small></div></div>}
    <details><summary>Inspect predictions, timing and sources</summary><p className="analyst-note">{item.eventDefinition}. One frozen vote per account. Analysts were published by the baseline retrieval cutoff; different forecast ages and shared models remain confounders. Baseline model issue time is unavailable. Reference point: {item.latitude}, {item.longitude}; provider grid: {item.baseline.latitude}, {item.baseline.longitude}.</p><div className="comparison-table-wrap"><table><thead><tr><th>Analyst</th><th>Prediction</th><th>Published</th><th>{s.scoreName}</th></tr></thead><tbody>{item.claims.map(c => <tr key={c.account}><td><a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.account} <ExternalLink size={11} /></a><details><summary>Claim and review</summary><p>{c.quote}</p><p>{c.interpretationNote}</p><small>Evidence revision {c.evidenceRevision} · captured {stamp(c.capturedAt)} · registered {stamp(c.registeredAt)}</small></details></td><td>{c.value} {item.unit}</td><td>{stamp(c.issuedAt)}</td><td>{number(s.analystScores.find(a => a.account === c.account)?.score ?? null)}</td></tr>)}</tbody></table></div><p className="analyst-note">Organizations represented: {s.organizations.join(', ')}. Account count is not a count of independent forecasting systems.</p><a href={item.baseline.sourceUrl} target="_blank" rel="noreferrer">Baseline documentation <ExternalLink size={12} /></a>{item.outcome && <p><a href={item.outcome.sourceUrl} target="_blank" rel="noreferrer">Observation source <ExternalLink size={12} /></a> · {item.outcome.note}</p>}</details>
    {!item.outcome && <OutcomeForm item={item} refresh={refresh} />}
  </article>;
}

function ClaimForm({ evidence, refresh }: { evidence: Evidence[]; refresh: () => void }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [selected, setSelected] = useState('');
  const eligible = evidence.filter(e => e.candidate.evidenceClass === 'forecast' && e.source.publishedAt && e.location?.precision === 'town');
  const source = eligible.find(e => e.id === selected);
  return <details className="comparison-entry"><summary>Register a comparable prediction</summary><p>Choose an advance prediction with a resolved publication time and a named town. Review an explicitly stated numeric value and exact future hour. Do not turn “likely”, a range, a regional outlook or a daily probability into an hourly point prediction.</p>
    {!eligible.length ? <p className="analyst-empty">No captured reports meet the location and timestamp requirements yet. Collect shortlisted analysts; broad or vague claims remain in the insight digest below.</p> : <form onSubmit={async event => { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api('/api/comparisons', { evidenceId: f.get('evidenceId'), metric: f.get('metric'), validAt: f.get('validAt') + ':00Z', value: Number(f.get('value')), quote: f.get('quote'), interpretationNote: f.get('interpretationNote'), reviewed: true }); refresh(); event.currentTarget?.reset(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>
      <label>Captured source<select name="evidenceId" required value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose a captured forecast</option>{eligible.map(e => <option key={e.id} value={e.id}>@{e.source.account} · {e.location!.name} · {e.candidate.title}</option>)}</select></label>
      {source && <details><summary>Read captured evidence before normalizing</summary><p className="captured-text">{source.source.text}</p>{source.source.media.filter(m => m.inspected).map((m,i) => <p key={i}>{m.observedText}</p>)}</details>}
      <div className="analyst-form-grid"><label>Metric<select name="metric"><option value="temperature_c">2 m temperature (°C), at the hour</option><option value="precipitation_mm">Total precipitation (mm), preceding hour</option><option value="precipitation_probability">Chance of &gt;0.1 mm (%), preceding hour</option></select></label><label>Exact target hour (UTC)<input name="validAt" type="datetime-local" step="3600" required /></label><label>Explicit numeric prediction<input name="value" type="number" step="any" required /></label></div>
      <label>Exact prediction quotation<textarea name="quote" required minLength={3} maxLength={1000} /></label><label>Explain the matching location, units and time window<textarea name="interpretationNote" required minLength={10} maxLength={1000} /></label>
      <label className="review-check"><input type="checkbox" required /> I verified the source explicitly supports this value, metric and exact window at the town reference point. This is a reviewed extraction, not an AgArena forecast.</label>
      <p>A matching provider baseline is frozen before the period starts. Later-issued predictions cannot join an older baseline. Each analyst gets one immutable prediction per case.</p>
      {error && <p role="alert" className="inline-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? 'Freezing comparison…' : 'Freeze prediction and baseline'}</button>
    </form>}
  </details>;
}

export default function AnalystPanel({ mode, onCollect, collectionBusy }: { mode: 'live' | 'demo'; onCollect: (account: string) => void; collectionBusy: boolean }) {
  const [data, setData] = useState<AnalystDashboard | null>(null), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  const refresh = () => setRevision(n => n+1);
  useEffect(() => { const abort = new AbortController(); setError(''); fetch('/api/analysts?mode=' + mode, { signal: abort.signal }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); if (d.mode !== mode) throw new Error('Unexpected data mode'); if (!abort.signal.aborted) setData(d); }).catch(e => { if (!abort.signal.aborted) setError(e.message); }); return () => abort.abort(); }, [mode,revision]);
  return <div className="analyst-panel"><section className="analyst-intro"><div><span className="eyebrow">A WIDER VIEW</span><h2>Six voices. Comparable claims.</h2><p>Five additional analysts join the existing Ontario source. Read what they suggest, see where they differ, and evaluate only predictions that describe the same event.</p></div><button className="text-button" onClick={refresh}><RefreshCw size={15} /> Refresh</button></section>
    {error && <div className="error-banner" role="alert">{error}</div>}{!data || data.mode !== mode ? <p role="status">Loading analysts and comparisons…</p> : <>
    <div className="analyst-section-heading"><h2><Users size={21} /> Analyst shortlist</h2><span>5 new · 1 existing</span></div><p className="analyst-note">{data.note} Identity sources checked September 12, 2026. A profile link does not imply a fresh post has been collected.</p>
    <div className="analyst-directory">{data.analysts.map(a => <article className="analyst-card" key={a.account}><div><span className="analyst-avatar">{a.name.split(' ').map(s => s[0]).slice(0,2).join('')}</span><div><h3>{a.name}</h3><a href={a.profileUrl} target="_blank" rel="noreferrer">@{a.account} <ExternalLink size={11} /></a></div><span className="tag neutral">{a.existing ? 'Existing' : 'Shortlisted'}</span></div><p>{a.focus}</p><small>{a.organization}</small><footer><a href={a.verificationUrl} target="_blank" rel="noreferrer">Identity source <ExternalLink size={11} /></a><button className="text-button" disabled={mode === 'demo' || collectionBusy} onClick={() => onCollect(a.account)}><ArrowDownToLine size={13} /> Collect</button></footer></article>)}</div>
    <details className="comparison-entry research-examples"><summary>Five sourced insight examples · historical research</summary><p>These dated public examples show the different kinds of reasoning on the shortlist. Together they suggest checking storm timing, local effects and model uncertainty, while keeping seasonal outlooks separate from short-term decisions. This is an editorial synthesis, not a current consensus forecast. None of these examples is scored or counted as a live capture.</p>{data.researchExamples.map(e => <article key={e.account}><strong>@{e.account} · {e.publishedDate}</strong><p>{e.summary}</p><small>{e.treatment}</small><p><a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.sourceType} <ExternalLink size={12} /></a></p></article>)}</details>
    <div className="analyst-section-heading"><h2>Prediction comparisons</h2><span>{data.comparisons.length} matched cases</span></div>
    <p className="analyst-note">Provider forecasts are the status quo baseline. Later station observations or reviewed radar precipitation estimates provide the verification target. Scores describe these samples; no analyst ranking is claimed.</p>
    {mode === 'demo' && <div className="comparison-demo-notice">All numbers and “Demo analyst” identities below are invented. They are not predictions by the shortlisted people.</div>}
    {!data.comparisons.length && <div className="analyst-empty"><h3>No matched live predictions yet.</h3><p>Broad or qualitative reports cannot be honestly scored. Use Demo scenario for a complete, clearly labeled scoring example.</p></div>}
    <div className="comparison-list">{data.comparisons.map(item => <CaseCard key={item.id} item={item} refresh={refresh} />)}</div>{mode === 'live' && <ClaimForm evidence={data.evidence} refresh={refresh} />}
    <div className="analyst-section-heading"><h2>Attributed insight digest</h2><span>{data.groups.length} topic groups</span></div><p className="analyst-note">Grouped by named location, hazard and publication date. These groups organize reading; they do not assert a shared prediction window or independent consensus. Exact copied text is counted once.</p>
    {!data.groups.length && <p className="analyst-empty">No source insights captured in this mode.</p>}<div className="insight-groups">{data.groups.map(g => <section className="insight-group" key={g.key}><div className="section-heading"><h3>{g.location} · {g.hazard}</h3><span>{g.accounts.length} account{g.accounts.length === 1 ? '' : 's'}</span></div><small>{g.date}</small>{g.reports.map(r => <article key={r.id}><a href={r.sourceUrl} target="_blank" rel="noreferrer">{mode === 'demo' ? 'Synthetic source' : '@' + r.account} <ArrowRight size={12} /></a><p>{r.summary}</p><small>{r.scoreability}</small></article>)}</section>)}</div>
    <section className="baseline-guide"><h3>What does the baseline tell us?</h3><p>Open-Meteo snapshots preserve a forecast available before the event. A radar image describes precipitation echoes at its image time; it cannot stand in for a future probability, an hourly accumulation or a ground measurement. Reviewed observations retain their source, units, coverage and location.</p><a href="https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/radar-overview/interpretation-rain-snow.html" target="_blank" rel="noreferrer">ECCC radar interpretation <ExternalLink size={12} /></a><a href="https://open-meteo.com/en/docs" target="_blank" rel="noreferrer">Provider metric definitions <ExternalLink size={12} /></a></section>
    </>}
  </div>;
}
