import { test } from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createApp } from '../server/app.ts';
import { Store } from '../server/store.ts';
import type { Dashboard, Job, Alert, Forecast } from '../src/contracts.ts';
import { testCapture, testWeather } from './test-data.ts';

const exec = promisify(execFile);
test('real HTTP API and CLI workflow: wait, inspect, import, complete, forecast, acknowledge, persist', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'agarena-http-'));
  const database = join(directory, 'api.sqlite');
  const store = new Store(database);
  let providerFails = false;
  const fetcher: typeof fetch = async () => {
    if (providerFails) return new Response('', { status: 503 });
    const data = testWeather(new Date()); data.hourly.precipitation_probability[3] = 85;
    return new Response(JSON.stringify(data));
  };
  const server = createApp(store, fetcher).listen(0, '127.0.0.1');
  await once(server, 'listening');
  const address = server.address(); assert.ok(address && typeof address !== 'string');
  const base = `http://127.0.0.1:${address.port}`;
  t.after(async () => { await new Promise<void>(resolve => server.close(() => resolve())); store.close(); });
  const request = (path: string, method = 'GET', body?: unknown) => fetch(base + path, { method, headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const health = await request('/api/health'); assert.equal(health.status, 200); assert.equal((await health.json()).collector, 'host-assisted');
  assert.equal((await fetch(base + '/api/health', { headers: { Origin: 'https://evil.test' } })).status, 403);
  assert.equal((await request('/api/unknown')).status, 404);
  assert.equal((await request('/api/captures', 'POST', {})).status, 400);
  assert.equal((await fetch(base + '/api/captures', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{' })).status, 400);
  assert.equal((await request('/api/forecast/monkton?threshold=nan')).status, 400);
  assert.equal((await request('/api/forecast/unsupported')).status, 404);
  const initial = await (await request('/api/dashboard')).json() as Dashboard; assert.equal(initial.evidence.length, 0);
  const demo = await (await request('/api/dashboard?mode=demo')).json() as Dashboard; assert.ok(demo.evidence.every(e => e.source.kind === 'demo'));

  const created = await request('/api/jobs', 'POST', {}); assert.equal(created.status, 201);
  const job = await created.json() as Job; assert.equal(job.status, 'waiting_for_agent'); assert.equal(job.capturedCount, 0);
  const duplicateJob = await (await request('/api/jobs', 'POST', {})).json() as Job; assert.equal(duplicateJob.id, job.id);
  const prompt = await (await request(`/api/jobs/${job.id}/prompt`)).text(); assert.match(prompt, /does not start an agent/);
  assert.equal((await request(`/api/jobs/${job.id}`, 'PATCH', { status: 'completed', evidenceIds: [] })).status, 409);
  assert.equal((await request(`/api/captures?job=${job.id}`, 'POST', testCapture(new Date()))).status, 409);
  assert.equal((await request(`/api/jobs/${job.id}`, 'PATCH', { status: 'collecting' })).status, 200);

  const old = testCapture(new Date(Date.parse(job.createdAt) - 60000));
  assert.equal((await request(`/api/captures?job=${job.id}`, 'POST', old)).status, 400);
  const packet = testCapture(new Date());
  packet.source.text = 'Invented integration test: Southern #Ontario outlook.';
  packet.candidate.placeQuery = 'Southern Ontario'; packet.candidate.locationQuote = 'Southern #Ontario'; packet.candidate.evidenceClass = 'forecast';
  packet.source.media = [{ url: 'https://pbs.twimg.com/media/invented-test.png', kind: 'photo', inspected: true, description: 'Synthetic automated test image description, not a real inspection.', observedText: 'Southern Ontario' }];
  packet.candidate.imageFindings = ['Synthetic automated test finding.'];
  const file = join(directory, 'test-capture.json'); await writeFile(file, JSON.stringify(packet));
  const invalidFile = join(directory, 'invalid-captures.json'); await writeFile(invalidFile, JSON.stringify([packet, {}]));
  await assert.rejects(exec(process.execPath, ['--import', 'tsx', 'scripts/import-capture.ts', invalidFile, '--job', job.id], { env: { ...process.env, AGARENA_API_URL: base } }));
  assert.equal(store.evidence().length, 0, 'all packets validated before mutation');
  const cli = await exec(process.execPath, ['--import', 'tsx', 'scripts/import-capture.ts', file, '--job', job.id], { env: { ...process.env, AGARENA_API_URL: base } });
  assert.match(cli.stdout, /Collection job completed/);
  const finished = await (await request(`/api/jobs/${job.id}`)).json() as Job;
  assert.equal(finished.status, 'completed'); assert.equal(finished.capturedCount, 1);
  const dashboard = await (await request('/api/dashboard')).json() as Dashboard;
  assert.equal(dashboard.counts.total, 1); assert.equal(dashboard.counts.mapped, 1); assert.equal(dashboard.counts.images, 1);
  assert.equal(dashboard.evidence[0].temporalStatus, 'outlook'); assert.equal(dashboard.evidence[0].independentEvidence, 1);
  assert.equal((await request(`/api/jobs/${job.id}`, 'PATCH', { status: 'collecting' })).status, 409);
  const repeated = await request('/api/captures', 'POST', packet); assert.equal(repeated.status, 200); assert.equal((await repeated.json()).duplicate, true);

  const nextJob = await (await request('/api/jobs', 'POST', {})).json() as Job;
  await request(`/api/jobs/${nextJob.id}`, 'PATCH', { status: 'collecting' });
  assert.equal((await request(`/api/jobs/${nextJob.id}`, 'PATCH', { status: 'completed', evidenceIds: [dashboard.evidence[0].id] })).status, 400, 'unrelated existing evidence cannot complete a new job');
  for (let i = 0; i < 3; i++) assert.equal((await request(`/api/captures?job=${nextJob.id}`, 'POST', testCapture(new Date(), `100000000000000001${i}`))).status, 201);
  assert.equal((await request(`/api/captures?job=${nextJob.id}`, 'POST', testCapture(new Date(), '1000000000000000020'))).status, 409);
  assert.equal((await request(`/api/jobs/${nextJob.id}`, 'PATCH', { status: 'cancelled' })).status, 200);

  const outlook = await (await request('/api/forecast/monkton')).json() as { forecast: Forecast; alerts: Alert[] };
  assert.equal(outlook.forecast.status, 'live'); assert.equal(outlook.forecast.provider, 'Open-Meteo');
  const rain = outlook.alerts.find(a => a.kind === 'rain'); assert.ok(rain);
  assert.equal((await request(`/api/alerts/${encodeURIComponent(rain.id)}/acknowledge`, 'POST', {})).status, 200);
  const cached = await (await request('/api/forecast/monkton')).json() as typeof outlook;
  assert.equal(cached.forecast.status, 'cached'); assert.equal(cached.alerts.find(a => a.id === rain.id)?.acknowledged, true);
  providerFails = true;
  const unavailable = await (await request('/api/forecast/huron')).json() as typeof outlook;
  assert.equal(unavailable.forecast.status, 'unavailable'); assert.deepEqual(unavailable.forecast.hours, []);
  assert.equal(unavailable.alerts[0].kind, 'unknown');
  const persisted = new Store(database);
  assert.equal(persisted.jobs().find(j => j.id === job.id)?.status, 'completed');
  assert.equal(persisted.acknowledged(rain.id), true); assert.equal(persisted.evidence().length, 4); persisted.close();
});
