import {CloudRain,Wind,NotebookPen,Clock,ArrowUpRight,Info} from 'lucide-react';
type RecordBrief={status:string;as_of:string;forecast:{id:string;rain_mm:number;issued_at:string;available_at:string;wind_m_s:number;hourly:{hour:number;rain_mm:number}[]}|null;observation:{text:string;observed_at:string;observer:string;method:string;review_status:string}};
const time=(value:string)=>new Date(value).toLocaleString('en-CA',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'America/Toronto'})+' EDT';
export function EvidenceStory({brief}:{brief:RecordBrief|null}){
 if(!brief)return <p>Loading evidence…</p>;
 const forecast=brief.forecast;
 return <div className="evidence-story"><div className="evidence-kicker">THE EVIDENCE AT A GLANCE <span>SIMULATED</span></div><article className="evidence-record"><div className="record-heading"><span className="record-icon"><CloudRain size={19}/></span><div><h3>{forecast?'Overnight rainfall outlook':'Forecast unavailable'}</h3><small>Regional model output · {forecast?time(forecast.issued_at):'unavailable'}</small></div><span className={'record-badge '+(brief.status==='fresh'?'':'aged')}>{brief.status==='fresh'?'Available':brief.status}</span></div>{forecast?<><div className="record-metrics"><div><strong>{forecast.rain_mm}<small> mm</small></strong><span>24-hour accumulation</span></div><div><strong>{Math.round(forecast.wind_m_s*3.6)}<small> km/h</small></strong><span>Wind from SSW</span></div></div><p>The scenario places most rainfall between 23:00 Saturday and 11:00 Sunday, local time. Rainfall within an individual field may differ from the 3 km grid value.</p><div className="evidence-rain" aria-label="Simulated rain totals for four six-hour periods">{forecast.hourly.slice(0,4).map((p,i)=><div key={p.hour}><b>{p.rain_mm} mm</b><i style={{height:6+p.rain_mm*8}}/><small>{['Sat 11–17','Sat 17–23','Sat 23–05','Sun 05–11'][i]}</small></div>)}</div><div className="record-foot"><Wind size={13}/>Single model scenario · uncertainty not quantified</div>{brief.status!=='fresh'&&<p className="evidence-warning">Historical context only. This run is too old to describe current conditions.</p>}</>:<p>No usable model record in this replay. A missing forecast cannot establish dry or accessible conditions.</p>}</article>
 <article className="evidence-record"><div className="record-heading"><span className="record-icon note"><NotebookPen size={18}/></span><div><h3>Access-track inspection</h3><small>{brief.observation.observer}</small></div><span className="record-badge aged">Stale</span></div><blockquote>“{brief.observation.text}”</blockquote><div className="note-metadata"><span><Clock size={12}/>Observed {time(brief.observation.observed_at)}</span><span>{brief.observation.method}</span><span>Review: {brief.observation.review_status} · Simulated field note</span></div><div className="record-foot">This describes the last visit, not today’s ground conditions.</div></article>
 <section className="evidence-gap"><Info size={17}/><div><h3>What would make this more useful?</h3><p>A current rain-gauge total and an updated access-track inspection. Neither is available in this scenario.</p></div></section>
 {forecast&&<div className="evidence-lineage"><div className="evidence-kicker">HOW THIS BRIEF WAS ASSEMBLED</div><div><span>01</span><p><b>Model run selected</b><small>{forecast.id==='cycle-12'?'12:00 UTC cycle':'06:00 UTC cycle'} · published {time(forecast.issued_at)}</small></p></div><div><span>02</span><p><b>Availability checked</b><small>Available {time(forecast.available_at)} · cutoff {time(brief.as_of)}</small></p></div><div><span>03</span><p><b>Local evidence kept separate</b><small>The old scout note does not confirm forecast rain or field access.</small></p></div></div>}
 </div>;
}
