import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Sprout,Layers,Map,ArrowUpRight,ChevronDown,ChevronRight,CloudRain,Wind,Thermometer,Clock,ShieldCheck,Info,X,Plus,Minus,LocateFixed,Download,ArrowRight,FlaskConical,Search,Check,LayoutGrid} from 'lucide-react';
import './style.css';
import {XSource} from './XSource';
import {EvidenceStory} from './EvidenceStory';
type Field={id:string;name:string;crop:string;area:number;location:string};
type Forecast={id:string;source_name:string;source_version:string;initialization_at:string;issued_at:string;available_at:string;ingested_at:string;valid_from:string;valid_until:string;native_resolution_m:number;temperature_K:number;wind_m_s:number;rain_mm:number;accumulation_start:string;accumulation_end:string;calibration:string;hourly:{hour:number;temperature_K:number;rain_mm:number}[]};
type Brief={field:Field;as_of:string;status:string;explanation:string;forecast:Forecast|null;rule_version:string;observation:{status:string;observed_at:string;text:string;observer:string;method:string;review_status:string};missing_inputs:string[]};
const stamp=(s:string)=>new Date(s).toLocaleString('en-CA',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})+' UTC';
async function api(path:string,options?:RequestInit){const r=await fetch('/v1/'+path,options);if(!r.ok)throw Error((await r.json()).code);return r.json()}
function App(){
 const [tenant,setTenant]=useState('alpha'),[fields,setFields]=useState<Field[]>([]),[selected,setSelected]=useState('north'),[brief,setBrief]=useState<Brief|null>(null),[drawer,setDrawer]=useState(false),[scenario,setScenario]=useState('normal'),[asOf,setAsOf]=useState('2026-09-12T15:00:00Z'),[horizon,setHorizon]=useState(24),[zoom,setZoom]=useState(1),[view,setView]=useState('map'),[error,setError]=useState(''),[query,setQuery]=useState(''),[unit,setUnit]=useState('C'),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setFields([]);setBrief(null);setLoading(true);api(`demo-session?tenant=${tenant}`,{method:'POST'}).then(()=>api('fields')).then((f:Field[])=>{if(active){setFields(f);setSelected(f[0].id)}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[tenant]);
 useEffect(()=>{if(!fields.some(f=>f.id===selected))return;let active=true;setLoading(true);setBrief(null);api(`fields/${selected}/brief?as_of=${asOf}&scenario=${scenario}`).then(b=>{if(active){setBrief(b);setError('')}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[fields,selected,asOf,scenario]);
 const replayFresh=scenario==='normal'&&['2026-09-12T15:00:00Z','2026-09-12T13:00:00Z'].includes(asOf);
 const dialogRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!drawer)return;const previous=document.activeElement as HTMLElement;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(false);if(e.key==='Tab'){const items=dialogRef.current?.querySelectorAll<HTMLButtonElement>('button');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus()}},[drawer]);
 const temp=(k:number)=>Math.round(unit==='C'?k-273.15:(k-273.15)*9/5+32);
 const filtered=fields.filter(f=>f.name.toLowerCase().includes(query.toLowerCase()));
 async function exportBrief(){try{const b=await api(`fields/${selected}/export?as_of=${asOf}&scenario=${scenario}`);const u=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`agarena-${selected}-synthetic.json`;a.click();URL.revokeObjectURL(u)}catch(e){setError(String(e))}}
 return <div className="app"><aside className="rail"><a className="brand" href="/" aria-label="AgArena home"><Sprout size={27}/></a><button className="rail-button active" aria-label="Field workspace" onClick={()=>setView('map')}><LayoutGrid/></button><button className="rail-button" aria-label="Field list" onClick={()=>setView('list')}><Map/></button><button className="rail-button" aria-label="Inspect evidence" onClick={()=>setDrawer(true)}><Layers/></button><div className="rail-bottom"><span className="rail-line"/><ShieldCheck size={20}/><span className="avatar">{tenant==='alpha'?'AL':'BE'}</span></div></aside>
 <div className="shell"><header><div className="wordmark">AgArena<span>FIELD INTELLIGENCE</span></div><div className="header-right"><span className="demo-badge"><FlaskConical size={13}/> Synthetic demo</span><label className="tenant"><span className="small-avatar">{tenant==='alpha'?'A':'B'}</span><select aria-label="Demo organization" value={tenant} onChange={e=>setTenant(e.target.value)}><option value="alpha">Alpha farms</option><option value="beta">Beta farms</option></select></label></div></header>
 <main><div className="heading"><div><div className="eyebrow">YOUR LAND. A CLEARER PICTURE.</div><h1>Field overview<span>.</span></h1><p>Understand what’s changing. Know where to look next.</p></div><button className="outline" onClick={exportBrief} disabled={!brief}><Download size={15}/> Export field brief</button></div>
 <div className="context-bar"><div><span className="live-dot"/>Local evidence workspace<span className="divider"/>September 12, 2026 <span className="muted">· UTC</span></div><button onClick={()=>setDrawer(true)}>Source & freshness <ArrowUpRight size={14}/></button></div>
 <section className="stats"><div className="stat"><span>FIELDS IN YOUR WORKSPACE <Map size={16}/></span><strong>{fields.length.toString().padStart(2,'0')}<small>{fields.reduce((s,f)=>s+f.area,0).toFixed(1)} hectares</small></strong><p>Private to your organization</p></div><div className="stat"><span>FORECAST COVERAGE <CloudRain size={17}/></span><strong>{replayFresh&&fields.length?1:0}<small>field with fixture data</small></strong><p>3 km model grid · synthetic</p></div><div className="stat"><span>LOCAL OBSERVATIONS <Clock size={16}/></span><strong className="amber">Unknown<small>fresh input needed</small></strong><p>Older reports don’t establish current conditions</p></div></section>
 <div className="workspace"><section className="map-card"><div className="map-toolbar"><div className="tabs"><button className={view==='map'?'chosen':''} onClick={()=>setView('map')}><Map size={15}/> Field map</button><button className={view==='list'?'chosen':''} onClick={()=>setView('list')}><LayoutGrid size={15}/> List view</button></div><span className="map-region">Chatham-Kent, ON <ChevronDown size={13}/></span></div>
 {view==='map'?<div className="map-area"><svg viewBox="0 0 820 480" role="img" aria-label="Schematic map of synthetic fields. Use the field list below to select a field."><defs><pattern id="land" width="170" height="130" patternUnits="userSpaceOnUse" patternTransform="rotate(-17)"><rect width="170" height="130" fill="#e5e8d6"/><rect x="4" y="4" width="96" height="65" fill="#d6dec5"/><rect x="104" y="4" width="62" height="120" fill="#e0dfc1"/><path d="M4 76h94v48H4z" fill="#dce3cb"/><path d="M12 10v52m9-52v52m9-52v52m9-52v52m9-52v52m9-52v52m9-52v52m9-52v52m9-52v52" stroke="#cbd5b9" opacity=".6"/></pattern><pattern id="unknown" width="9" height="9" patternUnits="userSpaceOnUse"><rect width="9" height="9" fill="#d4d9cc"/><path d="M0 9L9 0" stroke="#929b89" strokeWidth="1"/></pattern></defs><g transform={`translate(${410-410*zoom} ${240-240*zoom}) scale(${zoom})`}><rect width="820" height="480" fill="url(#land)"/><path d="M-40 405C140 330 110 390 255 355S400 240 560 285 735 230 870 125" fill="none" stroke="#c3d7d0" strokeWidth="25"/><path d="M-40 405C140 330 110 390 255 355S400 240 560 285 735 230 870 125" fill="none" stroke="#a9c5bd" strokeWidth="2"/><path d="M-40 120L850 398M160-20L10 500M603-30L450 510" stroke="#faf8e9" strokeWidth="11"/><path d="M-40 120L850 398M160-20L10 500M603-30L450 510" stroke="#c9c8b6" strokeWidth="1" strokeDasharray="5 6"/><text x="90" y="113" transform="rotate(17 90 113)" className="road-label">COUNTRY ROAD 14</text><text x="576" y="98" transform="rotate(-73 576 98)" className="road-label">FIELDSTONE ROAD</text><text x="560" y="292" className="river-label">Thames River</text>
 {fields.map((f,i)=>{const points=i===0?'260,124 409,170 374,285 226,239':'427,312 548,349 517,443 392,403';const unknown=f.id==='south'||!replayFresh;return <g key={f.id} className="field-shape" onClick={()=>setSelected(f.id)}><polygon points={points} fill={unknown?'url(#unknown)':'#d6b872'} fillOpacity=".8" stroke={selected===f.id?'#fff':'#6f795d'} strokeWidth={selected===f.id?5:2}/><polygon points={points} fill="none" stroke={selected===f.id?'#314c36':'transparent'} strokeWidth="2"/><g transform={i===0?'translate(265 188)':'translate(424 366)'}><rect x="-9" y="-20" rx="6" width="123" height="44" fill="#fff"/><circle cx="5" cy="1" r="4" fill={unknown?'#8b9385':'#bd8c3f'}/><text x="17" y="5" className="field-label">{f.name}</text></g></g>})}<text x="640" y="439" className="road-label">SYNTHETIC GEOGRAPHY</text></g></svg><div className="map-chip"><span className="live-dot"/>Forecast availability <ChevronDown size={12}/></div><div className="map-controls"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.8,z+.2))}><Plus size={17}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.8,z-.2))}><Minus size={17}/></button><button aria-label="Reset map" onClick={()=>setZoom(1)}><LocateFixed size={17}/></button></div><div className="map-legend"><span><i className="gold"/>Forecast</span><span><i className="hatch"/>Unknown</span></div><span className="map-disclaimer">Illustrative map · Not for navigation</span></div>:<div className="list-view"><h3>Your authorized fields</h3>{filtered.map(f=><button onClick={()=>setSelected(f.id)} key={f.id}><Sprout/><span><b>{f.name}</b><small>{f.crop} · {f.area} ha · Synthetic boundary</small></span><ChevronRight/></button>)}</div>}
 <div className="timeline"><div><Clock size={15}/><b>Forecast horizon</b><span>From Sep 12, 15:00 UTC</span></div><div className="segments">{[24,48,72].map(h=><button key={h} onClick={()=>setHorizon(h)} className={horizon===h?'selected':''}>{h}h</button>)}</div></div></section>
 <section className="brief-card"><div className="section-label">FIELD BRIEF <span>01 / EVIDENCE</span></div>{loading?<div className="loading">Loading authorized field evidence…</div>:brief?<><div className="field-title"><div className="crop-icon"><Sprout size={25}/></div><div><h2>{brief.field.name}</h2><p>{brief.field.crop} <span>·</span> {brief.field.area} ha</p></div><span className="private"><ShieldCheck size={13}/> Private</span></div><div className={'notice '+(brief.status==='fresh'?'':'unknown-notice')}><span className="notice-title">{brief.status==='fresh'?<CloudRain size={18}/>:<Info size={18}/>} {brief.status==='fresh'?'Rain in the outlook':'Conditions unknown'}</span><p>{brief.explanation}</p><span className="status-tag">{brief.status==='fresh'?'SYNTHETIC FORECAST':brief.status.toUpperCase()+' EVIDENCE'}</span></div><div className="weather-values"><div><Thermometer size={16}/><b>{brief.status==='fresh'&&brief.forecast?temp(brief.forecast.temperature_K)+'°'+unit:'—'}</b><span>Temperature</span></div><div><CloudRain size={16}/><b>{brief.status==='fresh'&&brief.forecast?brief.forecast.rain_mm+' mm':'—'}</b><span>Rain · next 24h</span></div><div><Wind size={16}/><b>{brief.status==='fresh'&&brief.forecast?Math.round(brief.forecast.wind_m_s*3.6)+' km/h':'—'}</b><span>Wind</span></div></div><div className="evidence-note"><Info size={16}/><p>Regional model context, not a field measurement. Recent local observations are missing.</p></div><button className="primary" onClick={()=>setDrawer(true)}>Explore the evidence <ArrowUpRight size={17}/></button><div className="brief-footer"><Clock size={12}/>{brief.forecast?'Issued '+stamp(brief.forecast.issued_at):'No usable forecast for this view'}</div></>:null}</section></div>
 <div className="lower-grid"><section className="fields-card"><div className="card-heading"><h3>Your fields <span>{fields.length}</span></h3><div className="search"><Search size={14}/><input placeholder="Find a field" aria-label="Find a field" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{filtered.length?filtered.map(f=><button className={'field-row '+(selected===f.id?'selected-row':'')} key={f.id} onClick={()=>setSelected(f.id)}><span className={'field-thumbnail '+(f.id==='south'?'soy':'')}><Sprout size={20}/></span><span className="field-meta"><b>{f.name}</b><small>{f.crop} <span>·</span> {f.area} ha</small></span><span className={'field-status '+(f.id==='south'?'muted':'')}>{f.id==='south'?'Input missing':replayFresh?'Forecast fixture':'Unknown'}</span><ChevronRight size={16}/></button>):<p className="empty">No fields match your search.</p>}</section><section className="outlook-card"><div className="card-heading"><h3>Weather ahead <span>{horizon} HOURS</span></h3><button className="unit" onClick={()=>setUnit(u=>u==='C'?'F':'C')}>°{unit} <ChevronDown size={12}/></button></div>{brief?.status==='fresh'&&brief.forecast?<><div className="chart" aria-label="Synthetic six-hour rainfall accumulations">{brief.forecast.hourly.filter(p=>p.hour<horizon).map(p=><div className="bar-column" key={p.hour}><span>{p.rain_mm}</span><div className="bar" style={{height:Math.max(3,p.rain_mm*16)}}/><small>+{p.hour}h</small></div>)}</div><div className="chart-legend"><span><i/>Rain per 6-hour interval (mm)</span><span>Synthetic · deterministic</span></div></>:<div className="empty-chart"><CloudRain/><span>No usable forecast in this view</span></div>}</section></div>
 {fields.length>0&&<XSource key={tenant} organization={tenant}/>}<section className="replay-panel"><div><FlaskConical size={18}/><span><b>Evidence replay lab</b><small>Explore how availability changes the field brief.</small></span></div><label>Decision time<select value={asOf} onChange={e=>setAsOf(e.target.value)}><option value="2026-09-12T15:00:00Z">Sep 12 · 15:00 UTC</option><option value="2026-09-12T13:00:00Z">Sep 12 · 13:00 UTC (delayed cycle)</option><option value="2026-09-12T05:00:00Z">Sep 12 · 05:00 UTC (before publication)</option><option value="2026-09-13T15:00:00Z">Sep 13 · 15:00 UTC (stale)</option></select></label><label>Source scenario<select value={scenario} onChange={e=>setScenario(e.target.value)}>{['normal','missing','stale','withdrawn','unsupported'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label></section>{error&&<p className="error" role="alert">Could not load evidence: {error}. Refresh to retry.</p>}<footer><span><Sprout size={14}/> Grounded in evidence. Built around your fields.</span><span>LOCAL DEMO <span>·</span> All fields and weather are synthetic</span></footer></main></div>
 {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}><section ref={dialogRef} className="drawer" role="dialog" aria-modal="true" aria-labelledby="evidence-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setDrawer(false)}}><div className="drawer-head"><span className="eyebrow">TRACE EVERY SIGNAL</span><button autoFocus aria-label="Close evidence" onClick={()=>setDrawer(false)}><X/></button></div><h2 id="evidence-title">Behind the field brief</h2><p className="drawer-intro">{brief?.field.name} · Synthetic evidence only</p><div className="provenance-banner"><ShieldCheck size={20}/><span>Scenario replay · September 12<small>Illustrative records, not live measurements or X posts.</small></span></div><EvidenceStory brief={brief}/><details className="technical-evidence"><summary>Full source record & timestamps</summary><h3>Forecast provenance</h3>{brief?.forecast?<dl>{Object.entries({'Source':brief.forecast.source_name,'Cycle':brief.forecast.id,'Model initialization':stamp(brief.forecast.initialization_at),'Issued':stamp(brief.forecast.issued_at),'Available':stamp(brief.forecast.available_at),'Ingested':stamp(brief.forecast.ingested_at),'Valid from':stamp(brief.forecast.valid_from),'Valid until':stamp(brief.forecast.valid_until),'Spatial support':'3 km model grid · not field resolved','Rain accumulation':stamp(brief.forecast.accumulation_start)+' → '+stamp(brief.forecast.accumulation_end),'Calibration':brief.forecast.calibration,'Rule version':brief.rule_version}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>:<p className="notice">Forecast unavailable: {brief?.status||'loading'}.</p>}</details><button className="primary" onClick={exportBrief}>Download evidence snapshot <Download size={16}/></button></section></div>}</div>
}
createRoot(document.getElementById('root')!).render(<App/>);
