import {useEffect,useState} from 'react';
import {ArrowUpRight,Radio,RefreshCw,Info} from 'lucide-react';
type Post={id:string;text:string;author:string;username:string;url:string;published_at:string;topics:string[];has_references:boolean};
type Source={status:string;message:string;posts:Post[];fetched_at:string|null;can_refresh?:boolean};
export function XSource({organization}:{organization:string}){
 const [source,setSource]=useState<Source|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setSource(null);setError('');const load=()=>fetch('/v1/sources/wxontario').then(async r=>{if(!r.ok)throw Error('Source status unavailable');return r.json()}).then(s=>{if(active)setSource(s)}).catch(e=>active&&setError(e.message));load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer)}},[organization]);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/v1/sources/wxontario/refresh',{method:'POST'});if(!r.ok)throw Error('Could not refresh source');setSource(await r.json())}catch(e){setSource(null);setError(String(e))}finally{setBusy(false)}}
 return <section className="x-source"><div className="card-heading"><h3><Radio size={15}/> Ontario weather reports <span>X SOURCE</span></h3><a href="https://x.com/WxOntario" target="_blank" rel="noreferrer">@WxOntario <ArrowUpRight size={13}/></a></div><div className="x-source-body"><div className="x-source-status"><div><b>{source?.status==='connected'?'Connected':source?.status==='ready'?'Ready to fetch':source?.status==='not_connected'?'Connection needed':source?.status.replaceAll('_',' ')||'Checking connection…'}</b><p>{source?.message||error||'Checking server-side X access.'}</p></div><button className="outline" onClick={refresh} disabled={busy||!source?.can_refresh}><RefreshCw size={14}/>{busy?'Fetching…':'Fetch up to 5 posts'}</button></div>{source?.status==='not_connected'&&<p className="x-setup">Set <code>X_BEARER_TOKEN</code> in the local server’s <code>.env</code> file, then restart. The token stays on the server.</p>}{source?.posts.map(post=><article className="x-post" key={post.id}><div><b>{post.author} <span>@{post.username}</span></b><a href={post.url} target="_blank" rel="noreferrer">View on X <ArrowUpRight size={12}/></a></div><p>{post.text}</p><div className="x-tags"><span>Unverified report</span>{post.topics.length?post.topics.map(t=><span key={t}>{t}</span>):<span>No weather keyword matched</span>}{post.has_references&&<span>References another post · not independent corroboration</span>}</div><small>Published {new Date(post.published_at).toLocaleString()} · Observation time and geographic support not established</small></article>)}<div className="x-boundary"><Info size={14}/><span>Text-only topic tagging. Posts are not verified observations or official alerts and do not alter field forecasts. Images and linked pages are not analyzed.</span></div>{source?.fetched_at&&<small className="x-fetched">Fetched {new Date(source.fetched_at).toLocaleString()} · Temporary snapshot expires after 15 minutes</small>}{error&&<p role="alert">{error}</p>}</div></section>
}
